### PR TITLE
Fixed computed values and changed the tests.

### LINKED ISSUE #4: Computeds don't update when dependencies change

### PR DESCRIPTION
**Pull request by stijnstroeve**

### CODE REVIEW

**Review by ManuelJager — COMMENTED** [review]
I don't know about generic type naming conventions in typescript, but maybe to make 'ValueType' shorter without losing context, you could rename it to 'TValue', like they do in c#

**Comment by stijnstroeve** [comment]
> I don't know about generic type naming conventions in typescript, but maybe to make 'ValueType' shorter without losing context, you could rename it to 'TValue', like they do in c#

From what I could find it is pretty conventional to name it ValueType or ValueT. I like ValueType more than ValueT, wbu?.

**Comment by ManuelJager** [comment]
> > I don't know about generic type naming conventions in typescript, but maybe to make 'ValueType' shorter without losing context, you could rename it to 'TValue', like they do in c#
> 
> From what I could find it is pretty conventional to name it ValueType or ValueT. I like ValueType more than ValueT, wbu?.

considering 'T' is pretty familiar to me (and i believe to others), I'd be happy to go with ValueT. Saves a little space without losing readability imo

**Comment by stijnstroeve** [comment]
> > > I don't know about generic type naming conventions in typescript, but maybe to make 'ValueType' shorter without losing context, you could rename it to 'TValue', like they do in c#
> > 
> > 
> > From what I could find it is pretty conventional to name it ValueType or ValueT. I like ValueType more than ValueT, wbu?.
> 
> considering 'T' is pretty familiar to me (and i believe to others), I'd be happy to go with ValueT. Saves a little space without losing readability imo

I have updated it to ValueT.

**Pull request merged**
